"""Codex CLI adapter for the video skill batch pipeline.

This mirrors the public surface of ``claude_cli_tools.py`` where practical, but
uses ``codex exec --json`` and Codex rollout JSONL files as the source of truth.
The returned ``session_id`` is generated by the child Codex process. The wrapper
never injects or fabricates a session id.
"""

import asyncio
import glob
import json
import os
import shutil
import signal
import time
from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional


# ========== Paths and constants ==========

from AutomaticSkillOptimization.args import CODEX_BIN, CODEX_SESSIONS_DIR, OUTPUT_DIR
from AutomaticSkillOptimization.utils import find_session_dir, safe_segment

# In-process mapping from canonical session id to the raw Codex event JSONL.
_SESSION_JSONL_BY_SESSION_ID: Dict[str, str] = {}
_SESSION_META_BY_SESSION_ID: Dict[str, Dict[str, Any]] = {}
_SESSION_USER_MESSAGE_BY_SESSION_ID: Dict[str, str] = {}


active_processes: set = set()


async def _stop_process_group(proc, log_func, reason: str, grace_seconds: int = 15):
    """Terminate a Codex subprocess and anything it spawned in its process group."""
    active_processes.discard(proc)
    if proc.returncode is not None:
        return

    log_func(f"Stopping subprocess pid={proc.pid} ({reason})")
    try:
        os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
    except ProcessLookupError:
        return
    except Exception as exc:
        log_func(f"Process-group SIGTERM failed ({exc}); falling back to terminate()")
        try:
            proc.terminate()
        except ProcessLookupError:
            return

    try:
        await asyncio.wait_for(proc.wait(), timeout=grace_seconds)
        return
    except asyncio.TimeoutError:
        log_func(f"Subprocess pid={proc.pid} did not stop in {grace_seconds}s; sending SIGKILL")

    try:
        os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
    except ProcessLookupError:
        return
    except Exception as exc:
        log_func(f"Process-group SIGKILL failed ({exc}); falling back to kill()")
        try:
            proc.kill()
        except ProcessLookupError:
            return
    await proc.wait()


# ========== JSONL helpers ==========


def _session_output_dir(session_name: str, session_id: str) -> str:
    return os.path.join(OUTPUT_DIR, f"{safe_segment(session_name)}_{safe_segment(session_id)}")


def load_jsonl_file(path: str) -> List[Dict[str, Any]]:
    if not path or not os.path.exists(path):
        return []
    records: List[Dict[str, Any]] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return records


def load_jsonl_text(text: str) -> List[Dict[str, Any]]:
    records: List[Dict[str, Any]] = []
    for line in (text or "").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return records


def write_jsonl_records(path: str, records: Iterable[Dict[str, Any]]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def find_rollout_by_session_id(session_id: Optional[str]) -> Optional[str]:
    if not session_id:
        return None
    pattern = os.path.join(CODEX_SESSIONS_DIR, "**", f"rollout-*{session_id}.jsonl")
    matches = glob.glob(pattern, recursive=True)
    if not matches:
        return None
    return max(matches, key=os.path.getmtime)


def find_latest_rollout_after(start_time: float) -> Optional[str]:
    pattern = os.path.join(CODEX_SESSIONS_DIR, "**", "rollout-*.jsonl")
    matches = [
        path for path in glob.glob(pattern, recursive=True)
        if os.path.getmtime(path) >= start_time - 2
    ]
    if not matches:
        return None
    return max(matches, key=os.path.getmtime)


def resolve_jsonl_path(session_id_or_path: Optional[str], output_dir: Optional[str] = None) -> Optional[str]:
    if session_id_or_path and os.path.isfile(session_id_or_path):
        return session_id_or_path

    if output_dir:
        for name in ("original_ReAct.jsonl", "codex_exec_events.jsonl", "ReAct_process.jsonl"):
            candidate = os.path.join(output_dir, name)
            if os.path.isfile(candidate):
                return candidate

    if session_id_or_path:
        cached = _SESSION_JSONL_BY_SESSION_ID.get(session_id_or_path)
        if cached and os.path.isfile(cached):
            return cached
        rollout = find_rollout_by_session_id(session_id_or_path)
        if rollout:
            return rollout

    return None


def extract_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return "" if content is None else str(content)

    parts: List[str] = []
    for item in content:
        if not isinstance(item, dict):
            continue
        item_type = item.get("type")
        if item_type in {"input_text", "output_text", "text"}:
            parts.append(item.get("text", ""))
        elif "text" in item:
            parts.append(str(item.get("text", "")))
    return "\n".join(p for p in parts if p)


def summarize_tool_result(value: Any) -> str:
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False)
    except TypeError:
        return str(value)


def summarize_codex_records(records: List[Dict[str, Any]], returncode: Optional[int] = None) -> Dict[str, Any]:
    session_id = None
    rollout_timestamp = None
    cli_version = None
    model_provider = None
    cwd = None
    last_agent_message = ""
    task_complete = None
    last_token_info = None
    tool_call_count = 0

    for rec in records:
        rec_type = rec.get("type")
        payload = rec.get("payload", {})

        # Current codex exec stdout uses a compact event schema:
        # thread.started / item.completed / turn.completed. The persisted
        # rollout JSONL still uses session_meta / response_item / event_msg.
        if rec_type == "thread.started":
            session_id = rec.get("thread_id") or session_id
            continue

        if rec_type == "item.completed":
            item = rec.get("item") or {}
            item_type = item.get("type")
            if item_type == "agent_message":
                last_agent_message = item.get("text") or last_agent_message
            elif item_type in {"tool_call", "function_call", "command_execution"}:
                tool_call_count += 1
            continue

        if rec_type == "turn.completed":
            task_complete = rec
            last_token_info = {"total_token_usage": rec.get("usage") or {}}
            continue

        if rec_type == "session_meta":
            session_id = payload.get("id") or session_id
            rollout_timestamp = payload.get("timestamp") or rollout_timestamp
            cli_version = payload.get("cli_version") or cli_version
            model_provider = payload.get("model_provider") or model_provider
            cwd = payload.get("cwd") or cwd
            continue

        if rec_type == "response_item":
            if payload.get("type") == "function_call":
                tool_call_count += 1
            elif payload.get("type") == "message" and payload.get("role") == "assistant":
                text = extract_text(payload.get("content"))
                if text:
                    last_agent_message = text
            continue

        if rec_type == "event_msg":
            ptype = payload.get("type")
            if ptype == "token_count" and payload.get("info"):
                last_token_info = payload.get("info")
            elif ptype == "task_complete":
                task_complete = payload
                last_agent_message = payload.get("last_agent_message") or last_agent_message

    usage = {}
    if isinstance(last_token_info, dict):
        usage = dict(last_token_info.get("total_token_usage") or {})
        if "cached_input_tokens" in usage and "cache_read_input_tokens" not in usage:
            usage["cache_read_input_tokens"] = usage.get("cached_input_tokens", 0)
        usage["model_context_window"] = last_token_info.get("model_context_window")

    duration_ms = None
    time_to_first_token_ms = None
    if task_complete:
        duration_ms = task_complete.get("duration_ms")
        time_to_first_token_ms = task_complete.get("time_to_first_token_ms")

    return {
        "session_id": session_id,
        "rollout_timestamp": rollout_timestamp,
        "cli_version": cli_version,
        "model_provider": model_provider,
        "cwd": cwd,
        "last_agent_message": last_agent_message,
        "duration_ms": duration_ms,
        "time_to_first_token_ms": time_to_first_token_ms,
        "usage": usage,
        "tool_call_count": tool_call_count,
        "terminal_reason": "completed" if task_complete else ("process_exit" if returncode is not None else None),
        "returncode": returncode,
    }


# ========== JSONL -> ReAct_process ==========

def jsonl_to_react_process(session_id, output_dir, rollout_path=None, user_message=None, records=None):
    """Extract a ReAct_process.json from Codex JSONL and copy the raw JSONL."""
    if records is None:
        path = rollout_path or resolve_jsonl_path(session_id, output_dir)
        records = load_jsonl_file(path) if path else []
    else:
        path = rollout_path
    if not records:
        return None

    result: List[Dict[str, Any]] = []
    user_text = user_message or _SESSION_USER_MESSAGE_BY_SESSION_ID.get(session_id)
    if user_text:
        result.append({"role": "user", "content": user_text})

    for rec in records:
        if rec.get("type") == "item.completed":
            item = rec.get("item") or {}
            item_type = item.get("type")
            if item_type == "agent_message" and item.get("text"):
                result.append({
                    "role": "assistant",
                    "content": [{
                        "type": "final_return",
                        "content": item.get("text", ""),
                    }],
                })
            elif item_type in {"tool_call", "function_call"}:
                result.append({
                    "role": "assistant",
                    "content": [{
                        "type": "tool_call",
                        "name": item.get("name", ""),
                        "arguments": summarize_tool_result(item.get("arguments") or item.get("input") or {}),
                    }],
                })
            elif item_type in {"tool_result", "function_call_output"}:
                result.append({
                    "role": "assistant",
                    "content": [{
                        "type": "tool_result",
                        "tool_name": item.get("call_id") or item.get("id", ""),
                        "content": summarize_tool_result(item.get("output") or item.get("text") or ""),
                    }],
                })
            elif item_type == "command_execution":
                command = item.get("command", "")
                output = item.get("aggregated_output", "")
                exit_code = item.get("exit_code")
                status = item.get("status")
                result.append({
                    "role": "assistant",
                    "content": [
                        {
                            "type": "tool_call",
                            "name": "exec",
                            "arguments": {"command": command},
                        },
                        {
                            "type": "tool_result",
                            "tool_name": "exec",
                            "content": output,
                            "details": {
                                "status": status,
                                "exit_code": exit_code,
                            },
                        },
                    ],
                })
            continue

        if rec.get("type") != "response_item":
            continue
        payload = rec.get("payload", {})
        ptype = payload.get("type")

        if ptype == "message":
            role = payload.get("role")
            if role not in {"user", "assistant"}:
                continue
            text = extract_text(payload.get("content"))
            if not text:
                continue
            if role == "user":
                result.append({"role": "user", "content": text})
            else:
                result.append({
                    "role": "assistant",
                    "content": [{
                        "type": "final_return",
                        "content": text,
                    }],
                })

        elif ptype == "reasoning":
            summary = payload.get("summary") or []
            thinking = extract_text(summary)
            if thinking:
                result.append({
                    "role": "assistant",
                    "content": [{"type": "thinking", "content": thinking}],
                })

        elif ptype == "function_call":
            result.append({
                "role": "assistant",
                "content": [{
                    "type": "tool_call",
                    "name": payload.get("name", ""),
                    "arguments": payload.get("arguments", ""),
                }],
            })

        elif ptype == "function_call_output":
            result.append({
                "role": "assistant",
                "content": [{
                    "type": "tool_result",
                    "tool_name": payload.get("call_id", ""),
                    "content": summarize_tool_result(payload.get("output", "")),
                }],
            })

    os.makedirs(output_dir, exist_ok=True)

    out_path = os.path.join(output_dir, "ReAct_process.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    raw_dst = os.path.join(output_dir, "original_ReAct.jsonl")
    try:
        if path and os.path.abspath(path) != os.path.abspath(raw_dst):
            shutil.copy(path, raw_dst)
    except Exception as e:
        print(f"Failed to copy {path} to {raw_dst}: {e}")

    summary = summarize_codex_records(records)
    summary["raw_jsonl_path"] = path

    return out_path


# ========== Cost and result statistics ==========

def calculate_cost_from_jsonl(session_id_or_path, output_dir=None):
    """Collect Codex token usage.

    Codex ChatGPT-plan runs do not expose billable USD cost in the local JSONL,
    so cost fields are kept numeric zero while token details are preserved.
    """
    path = resolve_jsonl_path(session_id_or_path, output_dir) 
    records = load_jsonl_file(path) if path else []
    summary = summarize_codex_records(records)
    usage = summary.get("usage") or {}

    inp = usage.get("input_tokens", 0) or 0
    out = usage.get("output_tokens", 0) or 0
    cached = usage.get("cached_input_tokens")
    cached_for_rate = cached or 0
    reasoning = usage.get("reasoning_output_tokens", 0) or 0
    total = usage.get("total_tokens", inp + out) or 0

    return {
        "input_tokens": inp,
        "output_tokens": out,
        "reasoning_output_tokens": reasoning,
        "cached_input_tokens": cached,
        "cache_read_input_tokens": cached,
        "total_tokens": total,
        "cache_hit_rate": cached_for_rate / inp if inp > 0 else 0,
        "model_context_window": usage.get("model_context_window"),
        "cost": {
            "input": 0.0,
            "output": 0.0,
            "cacheRead": 0.0,
            "cacheWrite": 0.0,
            "total": 0.0,
            "unit": "N/A",
        },
        "tool_call_count": summary.get("tool_call_count", 0),
        "duration_ms": summary.get("duration_ms"),
        "time_to_first_token_ms": summary.get("time_to_first_token_ms"),
        "session_id": summary.get("session_id"),
        "rollout_path": path,
    }


# ========== Codex CLI invocation ==========

async def codex_chat(
    session_name,
    message,
    cwd,
    timeout_seconds=10800,
    max_retries=3,
    retry_delay=60,
    log_file=None,
    overwrite_log=False,
    model=None,
    sandbox="danger-full-access",
):
    """Run Codex CLI non-interactively.

    Returns a dict compatible with the old ``claude_chat`` call sites. The
    returned ``session_id`` is generated by the child Codex process and matches
    the Codex-injected ``CODEX_THREAD_ID`` used by skills and output folders.
    If Codex exits before producing a session id, ``session_id`` is ``None``.
    """
    retry_errors = [
        "rate limit",
        "Rate limit",
        "overloaded",
        "Timed out connecting to",
        "Timed out waiting for",
        "connection error",
        "temporarily unavailable",
    ]

    def _log(msg):
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        line = f"[{ts}] [{session_name}] {msg}"
        print(line)
        if log_file:
            with open(log_file, "a", encoding="utf-8") as lf:
                lf.write(line + "\n")

    if overwrite_log and log_file:
        try:
            open(log_file, "w").close()
        except Exception:
            pass

    for attempt in range(max_retries):
        _log(f"Start Codex exec (attempt {attempt + 1}/{max_retries}), session_id=codex-generated")

        cmd = [
            CODEX_BIN,
            "exec",
            "--skip-git-repo-check",
            "--json",
            "-C",
            cwd,
            "--sandbox",
             sandbox,
        ]
        if sandbox == "danger-full-access":
            cmd.append("--dangerously-bypass-approvals-and-sandbox")
        if model:
            cmd.extend(["--model", model])
        cmd.append(message)

        start_time = time.time()
        try:
            child_env = {**os.environ}
            child_env["CODEX_THREAD_NAME"] = session_name
            # Do not leak the parent Codex thread id into the child run. Codex
            # should inject the child run's own CODEX_THREAD_ID for tools.
            child_env.pop("CODEX_THREAD_ID", None)

            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                env=child_env,
                start_new_session=True,
            )
            active_processes.add(proc)

            try:
                stdout_data, stderr_data = await asyncio.wait_for(
                    proc.communicate(), timeout=timeout_seconds
                )
            except asyncio.TimeoutError:
                await _stop_process_group(proc, _log, "timeout")
                err = f"Timeout after {timeout_seconds}s"
                _log(f"Error: {err}")
                if attempt < max_retries - 1:
                    await asyncio.sleep(retry_delay)
                    continue
                return {
                    "success": False,
                    "session_id": None,
                    "error": err,
                }
            except asyncio.CancelledError:
                await _stop_process_group(proc, _log, "cancelled")
                raise
            finally:
                active_processes.discard(proc)

            stdout_str = stdout_data.decode("utf-8", errors="replace")
            stderr_str = stderr_data.decode("utf-8", errors="replace")
            records = load_jsonl_text(stdout_str)
            summary = summarize_codex_records(records, returncode=proc.returncode)
            session_id = summary.get("session_id")
            storage_id = session_id or f"unknown_{int(start_time)}"
            output_dir = _session_output_dir(session_name, storage_id)

            os.makedirs(output_dir, exist_ok=True)
            events_path = os.path.join(output_dir, "original_ReAct.jsonl")
            if records:
                write_jsonl_records(events_path, records)

            rollout_path = find_rollout_by_session_id(session_id) if session_id else None
            if session_id and not rollout_path:
                rollout_path = find_latest_rollout_after(start_time)
            raw_path = rollout_path or events_path

            if rollout_path:
                rollout_summary = summarize_codex_records(
                    load_jsonl_file(rollout_path),
                    returncode=proc.returncode,
                )
                rollout_session_id = rollout_summary.get("session_id")
                if rollout_session_id and session_id and rollout_session_id != session_id:
                    _log(
                        "Warning: stdout thread_id does not match rollout session_meta id: "
                        f"{session_id} != {rollout_session_id}"
                    )
                for key, value in rollout_summary.items():
                    if value not in (None, "", {}, []):
                        if key == "last_agent_message" and summary.get("last_agent_message"):
                            continue
                        summary[key] = value

            meta_key = session_id or storage_id
            _SESSION_JSONL_BY_SESSION_ID[meta_key] = raw_path
            _SESSION_USER_MESSAGE_BY_SESSION_ID[meta_key] = message
            _SESSION_META_BY_SESSION_ID[meta_key] = {
                **summary,
                "session_id": session_id,
                "session_name": session_name,
                "storage_id": storage_id,
                "session_id_source": "codex" if session_id else "missing",
                "rollout_path": rollout_path,
                "events_path": events_path,
            }

            if raw_path and os.path.exists(raw_path):
                try:
                    jsonl_to_react_process(meta_key, output_dir, rollout_path=raw_path, user_message=message)
                except Exception as e:
                    _log(f"Warning: failed to create ReAct files: {e}")

            if log_file:
                with open(log_file, "a", encoding="utf-8") as lf:
                    lf.write(f"\n=== STDOUT JSONL ===\n{stdout_str[:50000]}\n")
                    if stderr_str.strip():
                        lf.write(f"\n=== STDERR ===\n{stderr_str[:10000]}\n")

            _log(f"Exit code: {proc.returncode}, session_id={session_id}")

            combined = stderr_str + stdout_str
            retry_hit = any(e in combined for e in retry_errors)
            if retry_hit and attempt < max_retries - 1:
                _log(f"Retry-able error detected, waiting {retry_delay}s...")
                await asyncio.sleep(retry_delay)
                continue

            content = summary.get("last_agent_message") or stdout_str
            return {
                "success": proc.returncode == 0,
                "session_id": session_id,
                "content": content,
                "stderr": stderr_str,
                "error": stderr_str if proc.returncode != 0 else None,
                "rollout_path": rollout_path,
                "events_path": events_path,
                "output_dir": output_dir,
                "duration_ms": summary.get("duration_ms"),
                "time_to_first_token_ms": summary.get("time_to_first_token_ms"),
                "usage": summary.get("usage"),
            }

        except Exception as e:
            err = str(e)
            _log(f"Exception: {err}")
            if attempt < max_retries - 1:
                await asyncio.sleep(retry_delay)
                continue
            return {
                "success": False,
                "session_id": None,
                "error": err,
            }

    return {
        "success": False,
        "session_id": None,
        "error": "Max retries exceeded",
    }




